apiVersion: v1
kind: Service
metadata:
  name: wp-back-service
  labels:
    app: wp-back
  namespace: wp
spec:
  type: NodePort
  selector:
    app: wp-back
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
      nodePort: 30011