apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-claim
  namespace: wp
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi