apiVersion: v1
kind: Service
metadata:
  name: wp-storage
  namespace: wp
  labels:
    app: wp-storage
spec:
  selector:
    app: wp-storage
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432