apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wp-storage
  namespace: wp
spec:
  serviceName: storage
  selector:
    matchLabels:
      app: wp-storage
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: wp-storage
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          envFrom:
          - configMapRef:
              name: wp-storage-config
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wp-claim