apiVersion: v1
kind: Service
metadata:
  name: wp-front-service
  labels:
    app: wp-front
  namespace: wp
spec:
  type: NodePort
  selector:
    app: wp-front
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
      nodePort: 30010